### ISSUE TITLE
INVALID TOCKEN?

### ISSUE THREAD

**Issue by cutehosting** [Halocrea/voice-chat-bot#39]
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@7.4.0
2 info using node@v15.6.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 4ms
5 timing config:load:builtin Completed in 4ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/root/voice-chat-bot-master-test/.npmrc Completed in 2ms
9 timing config:load:project Completed in 8ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 4ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 23ms
19 verbose npm-session 95e64ff5b85cc2ee
20 timing npm:load Completed in 40ms
21 timing command:run-script Completed in 376ms
22 timing command:start Completed in 379ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (node:events:379:20)
23 verbose stack     at maybeClose (node:internal/child_process:1065:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
24 verbose pkgid voice-chat-bot@0.1.2
25 verbose cwd /root/voice-chat-bot-master-test
26 verbose Linux 4.9.0-14-amd64
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
28 verbose node v15.6.0
29 verbose npm  v7.4.0
30 error code 1
31 error path /root/voice-chat-bot-master-test
32 error command failed
33 error command sh -c node ./build/index.js
34 verbose exit 1
(log)
![image](https://user-images.githubusercontent.com/80317979/111027864-3b4b1500-83f3-11eb-88b5-5b6f4f72d3e5.png)

**Comment by cutehosting** [comment]
![image](https://user-images.githubusercontent.com/80317979/111027910-70576780-83f3-11eb-8785-150787e37273.png)
I have put the tocken

**Comment by tepec** [comment]
Hey! Make sure you provide the environment variables in a file named `.env`; here I see you're in the file called `sample.env`.

**Comment by cutehosting** [comment]
Thank you so much
